---
- hosts: zabbix-servers
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  - name: Create root directory
    shell: mkdir /opt/zabbix-ldap-integration
    args:
      executable: /bin/bash
  - name: Clone Zabbix-LDAP-Integration repo
    git:
      repo: 'https://github.com/GLutzBR/zabbix-ldap-integration.git'
      dest: /opt/zabbix-ldap-integration
      clone: yes
      version: master
      update: no

  - name: Configure connection.conf
    shell: |
      echo 'http://{{ ansible_fqdn }}/zabbix
      zabbix
      password
      ldap://auth.example.com:389
      CN=Zabbix User Admin,OU=Zabbix,DC=example,DC=com
      password
      DC=example,DC=com
      CN=zabbix.admins,OU=Zabbix,DC=example,DC=com' > /opt/zabbix-ldap-integration/connection.conf
    args:
      executable: /bin/bash

  - name: Create Crontab to use the script
    cron:
      name: "Zabbix-LDAP-Integration"
      user: root
      minute: "*/30"
      job: "python3 /opt/zabbix-ldap-integration/zabbix_ldap_integration.py < connection.conf > /dev/null"
      state: absent

  handlers:
     - name: restart ssh
       service:
         name=sshd
         state=restarted
